# Generated by Django 5.1.6 on 2025-02-26 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuxilioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPleiteado', models.DateField()),
                ('dataConcedido', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BancoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CondicaoFisicaMentalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CotaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CursoModalidadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='EtniaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsavelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('telefone', models.IntegerField()),
                ('tipo', models.CharField(choices=[('mãe', 'Mãe'), ('pai', 'Pai'), ('responsável legal', 'Responsável Legal')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SegregacaoRendaCotaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadesSalarioPercapta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEscolaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CursoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=20)),
                ('nivelEnsino', models.CharField(choices=[('mestrado', 'Mestrado'), ('pós graduação', 'Pós Graduação'), ('superior', 'Superior'), ('médio', 'Médio'), ('técnico', 'Técnico'), ('fundamental', 'Fundamental'), ('tecnologo', 'Tecnólogo')], max_length=50)),
                ('ativo', models.BooleanField()),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.cursomodalidademodel')),
            ],
        ),
        migrations.CreateModel(
            name='DadosBancariosModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.IntegerField()),
                ('conta', models.IntegerField()),
                ('tipoConta', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=50)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.bancomodel')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=80)),
                ('cep', models.IntegerField()),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.estadomodel')),
            ],
        ),
        migrations.CreateModel(
            name='GFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.enderecomodel')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('hash', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.cursomodel')),
            ],
        ),
        migrations.CreateModel(
            name='AlunoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=80)),
                ('ivs', models.IntegerField()),
                ('rendaPercapta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dataNascimento', models.DateField()),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno'), ('integral', 'Integral')], max_length=80)),
                ('situacao', models.CharField(choices=[('matriculado', 'Matriculado'), ('aguardando colacao', 'Aguardando Colação'), ('transferido interno', 'Transferido Interno'), ('transferido externo', 'Transferido Externo'), ('formado', 'Formado'), ('cancelamento compulsório', 'Cancelamento Compulsório'), ('aguardando solicitar certificacao', 'Aguardando Solicitar Certificação')], max_length=50)),
                ('auxilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.auxiliomodel')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.categoriamodel')),
                ('condicaoFisicaMental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.condicaofisicamentalmodel')),
                ('cota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.cotamodel')),
                ('dadosBancarios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.dadosbancariosmodels')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.enderecomodel')),
                ('etnia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.etniamodel')),
                ('gf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.gfmodel')),
                ('matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='AE.matriculamodel')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.responsavelmodel')),
            ],
        ),
        migrations.AddField(
            model_name='cotamodel',
            name='tipoEscola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AE.tipoescolamodel'),
        ),
    ]
